const testData =
{
  model: {
    id: '62914465e1b8830a92f9f610',
    name: 'First Board',
    desc: '',
    descData: null,
    closed: false,
    idOrganization: '628e73fa7614854fe755f294',
    idEnterprise: null,
    pinned: false,
    url: 'https://trello.com/b/oMsvDFY2/first-board',
    shortUrl: 'https://trello.com/b/oMsvDFY2',
    prefs: {
      permissionLevel: 'org',
      hideVotes: false,
      voting: 'disabled',
      comments: 'members',
      invitations: 'members',
      selfJoin: true,
      cardCovers: true,
      isTemplate: false,
      cardAging: 'regular',
      calendarFeedEnabled: false,
      hiddenPluginBoardButtons: [],
      switcherViews: [Array],
      background: '62913d3f590b257bbb29ed8e',
      backgroundColor: null,
      backgroundImage: 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/original/78021e781717cdb8b47655989030afb3/photo-1653592328269-09c14b3628f9',
      backgroundImageScaled: [Array],
      backgroundTile: false,
      backgroundBrightness: 'light',
      backgroundBottomColor: '#b6ac9f',
      backgroundTopColor: '#abaca8',
      canBePublic: true,
      canBeEnterprise: true,
      canBeOrg: true,
      canBePrivate: true,
      canInvite: true
    },
    labelNames: {
      green: '',
      yellow: '',
      orange: '',
      red: '',
      purple: '',
      blue: '',
      sky: '',
      lime: '',
      pink: '',
      black: '',
      green_dark: '',
      yellow_dark: '',
      orange_dark: '',
      red_dark: '',
      purple_dark: '',
      blue_dark: '',
      sky_dark: '',
      lime_dark: '',
      pink_dark: '',
      black_dark: '',
      green_light: '',
      yellow_light: '',
      orange_light: '',
      red_light: '',
      purple_light: '',
      blue_light: '',
      sky_light: '',
      lime_light: '',
      pink_light: '',
      black_light: ''
    }
  },
  action: {
    id: '62985af29a42d113398e4e2a',
    idMemberCreator: '628e73c4b1c2958f42fab51b',
    data: {
      card: [Object],
      old: [Object],
      board: [Object],
      listBefore: [Object],
      listAfter: [Object]
    },
    appCreator: null,
    type: 'updateCard',
    date: '2022-06-02T06:38:42.765Z',
    limits: null,
    display: {
      translationKey: 'action_move_card_from_list_to_list',
      entities: [Object]
    },
    memberCreator: {
      id: '628e73c4b1c2958f42fab51b',
      activityBlocked: false,
      avatarHash: '2aed475f3dad6a6d0c739f24f43be181',
      avatarUrl: 'https://trello-members.s3.amazonaws.com/628e73c4b1c2958f42fab51b/2aed475f3dad6a6d0c739f24f43be181',
      fullName: 'Liz García',
      idMemberReferrer: null,
      initials: 'LG',
      nonPublic: {},
      nonPublicAvailable: true,
      username: 'lizgarcia78'
    }
  }
}